FROM python:3.12-slim-bookworm
ENV TZ=Asia/Shanghai

WORKDIR /app

COPY pyproject.toml ./
RUN pip install -r pyproject.toml && \
    playwright install firefox && \
    playwright install-deps firefox && \
    apt-get update && \
    apt-get install -y --no-install-recommends vim && \
    apt-get clean