# synology drive 配置信息
nas_username: ""
nas_password: ""
nas_address:
  - address: "192.168.1.2"
    port: 5000
    https: false

# mqtt 配置信息
mqtt:
  host: "192.168.1.2"
  port: 1883
  user: ""
  pass: ""
  client_id: "scraper-news"
